language: python
addons:
  apt:
    packages:
    - zlib1g-dev
    - libbz2-dev
    - liblzma-dev
    - libcurl4-gnutls-dev
    - libcurl4-nss-dev
    - libcurl4-openssl-dev
python:
  - "3.4"
sudo: false
install:
  - "source ./install_dependencies.sh"
script:
  - "python setup.py test"